name: geomod
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  geolocator: ^9.0.2
  real_volume: ^1.0.7
  #  perfect_volume_control: ^1.0.5
  flutter_background_service: ^2.4.6
  #  flutter_mute: ^0.0.4
  permission_handler: ^10.2.0
  screen_brightness: ^0.2.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  awesome_snackbar_content: ^0.1.3
  location: ^5.0.3
  connectivity: ^3.0.6
  wifi_info_flutter: ^2.0.2
  latlong2: ^0.9.0
  network_info_plus: ^4.1.0
  sensors_plus: ^3.1.0
  animate_do: ^3.1.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  awesome_notifications: ^0.8.2
  uni_links: ^0.5.1
  share_plus: ^7.2.1
  device_info: ^2.0.3
  firebase_messaging:
  flutter_local_notifications: ^16.3.2
  app_settings:
  http:
  upgrader: ^9.0.0
  flutter_image_compress:
  flutter_svg:
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - lib/core/locales/l10n/
    - lib/assets/ji.png
    - lib/assets/default.jpg
    - lib/assets/satellite.jpg
    - lib/assets/terrain.jpg
    - lib/assets/ringerradius.png
    - lib/assets/house.svg
    - lib/assets/college.svg
    - lib/assets/save.svg
    - lib/assets/work.svg
    - lib/assets/prayer.svg

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.otf
        - asset: fonts/SFPRODISPLAYMEDIUM.otf
        - asset: fonts/SFPRODISPLAYHEAVYITALIC.otf
        - asset: fonts/SFPRODISPLAYBOLD.otf

  