// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxdNWO3muHzZjb7yZsGHzrW707K8DBh6U',
    appId: '1:337845988150:web:06bf52a6a934a615dda197',
    messagingSenderId: '337845988150',
    projectId: 'ringerradius',
    authDomain: 'ringerradius.firebaseapp.com',
    storageBucket: 'ringerradius.appspot.com',
    measurementId: 'G-DRMMYY64MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1G-mFLDxsamYxpuPKaEu2WuoNtxzrXA',
    appId: '1:337845988150:android:3aadfda98d6854a1dda197',
    messagingSenderId: '337845988150',
    projectId: 'ringerradius',
    storageBucket: 'ringerradius.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsPXA-IIP9UL3c4tMWpiI5sDIxA1Wohc',
    appId: '1:337845988150:ios:8ca1123d53d5af8bdda197',
    messagingSenderId: '337845988150',
    projectId: 'ringerradius',
    storageBucket: 'ringerradius.appspot.com',
    iosBundleId: 'com.example.locationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClsPXA-IIP9UL3c4tMWpiI5sDIxA1Wohc',
    appId: '1:337845988150:ios:8ca1123d53d5af8bdda197',
    messagingSenderId: '337845988150',
    projectId: 'ringerradius',
    storageBucket: 'ringerradius.appspot.com',
    iosBundleId: 'com.example.locationApp',
  );
}
